# This workflow will run the tests with pytest and generate a test unit report

name: selenium-python

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install pipenv
      run: python3 -m pip install --upgrade pip && pip install pipenv

    - name: Install dependencies using Pipfile
      run: pipenv install --dev

    - name: Run tests with coverage
      run: pipenv run python -m pytest --verbose --junitxml=report.xml # create junit xml report with pytest

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        report_paths: '**/report.xml'
        detailed_summary: true
        include_passed: true

