# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: selenium-python

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]


permissions: # This is where we set permissions for the workflow specifically to wrtie junit results
  contents: write 
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Check the code in the respository

    - name: Set up Python
      uses: actions/setup-python@v2 # Set up the python environment
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip 
        pip install pytest pytest-cov pytest_bdd # install requred testing dependencies

    - name: Run tests with coverage
      run: |
        python -m pytest --verbose --junitxml=report.xml # create junit xml report with pytest

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3 # use this action to publish the junit report
      if : success() || failure() # Ensure to publish the report regardless of any failures in previous steps in the workflow
      with:
        report_paths: '**/junit.xml' # path the junit report
        detailed_summary: true # provide a detailed summary of the test results
        include_passed: true # include passed tests in the report
  
